### ISSUE TITLE
Developer setup

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#237]
**Describe the bug**
Setting up the conda environment as described [here](https://github.com/matchms/matchms#documentation-for-developers) causes an error.

**To Reproduce**
Follow the developer documentation.

**Expected behavior**
All dependencies for development should be installed.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows

**Additional context**
Error message:
```
(matchms-dev) C:\Users\473355\git\hechth\matchms>pip3 install --editable .[dev]  
Traceback (most recent call last):
  File "C:\Users\473355\Miniconda3\envs\matchms-dev\Scripts\pip3-script.py", line 5, in <module>
    from pip._internal.cli.main import main
  File "C:\Users\473355\Miniconda3\envs\matchms-dev\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\473355\Miniconda3\envs\matchms-dev\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\473355\Miniconda3\envs\matchms-dev\lib\site-packages\pip\_internal\cli\main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "C:\Users\473355\Miniconda3\envs\matchms-dev\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "C:\Users\473355\Miniconda3\envs\matchms-dev\lib\site-packages\pip\_internal\cli\parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "C:\Users\473355\Miniconda3\envs\matchms-dev\lib\site-packages\pip\_internal\configuration.py", line 21, in <module>
    from pip._internal.exceptions import (
  File "C:\Users\473355\Miniconda3\envs\matchms-dev\lib\site-packages\pip\_internal\exceptions.py", line 8, in <module>
    from pip._vendor.requests.models import Request, Response
  File "C:\Users\473355\Miniconda3\envs\matchms-dev\lib\site-packages\pip\_vendor\requests\__init__.py", line 43, in <module>
    from pip._vendor import urllib3
  File "C:\Users\473355\Miniconda3\envs\matchms-dev\lib\site-packages\pip\_vendor\urllib3\__init__.py", line 13, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\473355\Miniconda3\envs\matchms-dev\lib\site-packages\pip\_vendor\urllib3\connectionpool.py", line 40, in <module>
    from .response import HTTPResponse
  File "C:\Users\473355\Miniconda3\envs\matchms-dev\lib\site-packages\pip\_vendor\urllib3\response.py", line 157, in <module>
    class HTTPResponse(io.IOBase):
  File "C:\Users\473355\Miniconda3\envs\matchms-dev\lib\site-packages\pip\_vendor\urllib3\response.py", line 390, in HTTPResponse
    DECODER_ERROR_CLASSES += (brotli.error,)
AttributeError: module 'brotli' has no attribute 'error'
```

**Comment by florian-huber** [comment]
Thanks Helge!
That used to work, so I guess some dependencies changes/broke. Also makes me realize that we do not run any test on creating the `dev` environment. Should be done though.

**Comment by florian-huber** [comment]
Sorry, forget my last comment. That's actually not true, we do run the mentioned command in our tests: 
```
python -m pip install --upgrade pip
pip install -e .[dev]
```
(https://github.com/matchms/matchms/blob/master/.github/workflows/CI_build.yml)

What Python version did you use @hechth?
I guess that could be where the instructions go wrong. I will test is later and see if I can update the instructions.

**Comment by hechth** [comment]
It installs the default python 3.9.5 - should there be a different version?

**Comment by florian-huber** [comment]
I tested it locally (also Windows) but could not reproduce the error. I did also get python 3.9.5 though.
Since we currently only tested the package for python 3.7 and 3.8 I will still change the instructions.

The only other thing that I did differently is updating pip, which I just added to the instructions in the readme.
I also added a CI test for creating the [dev] environment --> #238.

The slightly updated instructions now are:
```
git clone https://github.com/matchms/matchms.git
cd matchms
conda create --name matchms-dev python=3.8
conda activate matchms-dev
# Install rdkit using conda, rest of dependencies can be installed with pip
conda install -c conda-forge rdkit
python -m pip install --upgrade pip
pip install --editable .[dev]
```

**Comment by hechth** [comment]
Seems to have been some local issue with miniconda3 - can confirm that the updated documentation now also works for me.

Thank you very much for the fast help!
