### ISSUE TITLE
`ModuleNotFoundError`: No module named 'matchms.filtering.filter_utils'

### ISSUE THREAD

**Issue by chanana** [matchms/matchms#456]
**Describe the bug**
Can't import the `Spectrum` class.

**To Reproduce**
1. in a fresh environment, I did: `poetry add matchms`. 
2. This fetched v0.21.0 of matchms
3. In my jupyter notebook, I did: 

```python
from matchms import Spectrum
```

and got:

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[14], line 1
----> 1 from matchms import Spectrum

File [~/code/new-metabolomics/.venv/lib/python3.9/site-packages/matchms/__init__.py:1](https://file+.vscode-resource.vscode-cdn.net/Users/shaurya/code/new-metabolomics/~/code/new-metabolomics/.venv/lib/python3.9/site-packages/matchms/__init__.py:1)
----> 1 from . import exporting, filtering, importing, networking, plotting, similarity
      2 from .__version__ import __version__
      3 from .calculate_scores import calculate_scores

File [~/code/new-metabolomics/.venv/lib/python3.9/site-packages/matchms/exporting/__init__.py:8](https://file+.vscode-resource.vscode-cdn.net/Users/shaurya/code/new-metabolomics/~/code/new-metabolomics/.venv/lib/python3.9/site-packages/matchms/exporting/__init__.py:8)
      1 """
      2 Functions for exporting mass spectral data
      3 ##########################################
   (...)
      6 can be exported to json, mgf, or msp files.
      7 """
----> 8 from .save_as_json import save_as_json
      9 from .save_as_mgf import save_as_mgf
     10 from .save_as_msp import save_as_msp

File [~/code/new-metabolomics/.venv/lib/python3.9/site-packages/matchms/exporting/save_as_json.py:4](https://file+.vscode-resource.vscode-cdn.net/Users/shaurya/code/new-metabolomics/~/code/new-metabolomics/.venv/lib/python3.9/site-packages/matchms/exporting/save_as_json.py:4)
      2 import json
      3 from typing import List
----> 4 from ..Spectrum import Spectrum
      5 from ..utils import fingerprint_export_warning
      8 def save_as_json(spectrums: List[Spectrum], filename: str):

File [~/code/new-metabolomics/.venv/lib/python3.9/site-packages/matchms/Spectrum.py:7](https://file+.vscode-resource.vscode-cdn.net/Users/shaurya/code/new-metabolomics/~/code/new-metabolomics/.venv/lib/python3.9/site-packages/matchms/Spectrum.py:7)
      5 from .Fragments import Fragments
      6 from .hashing import metadata_hash, spectrum_hash
----> 7 from .Metadata import Metadata
     10 class Spectrum:
     11     """Container for a collection of peaks, losses and metadata.
     12 
     13     Spectrum peaks are stored as :class:`~matchms.Fragments` object which can be
   (...)
     62 
     63     """

File [~/code/new-metabolomics/.venv/lib/python3.9/site-packages/matchms/Metadata.py:4](https://file+.vscode-resource.vscode-cdn.net/Users/shaurya/code/new-metabolomics/~/code/new-metabolomics/.venv/lib/python3.9/site-packages/matchms/Metadata.py:4)
      2 import numpy as np
      3 from pickydict import PickyDict
----> 4 from .filtering.add_precursor_mz import _add_precursor_mz_metadata
      5 from .filtering.add_retention import _add_retention
      6 from .filtering.interpret_pepmass import _interpret_pepmass_metadata

File [~/code/new-metabolomics/.venv/lib/python3.9/site-packages/matchms/filtering/__init__.py:42](https://file+.vscode-resource.vscode-cdn.net/Users/shaurya/code/new-metabolomics/~/code/new-metabolomics/.venv/lib/python3.9/site-packages/matchms/filtering/__init__.py:42)
     40 from .add_fingerprint import add_fingerprint
     41 from .add_losses import add_losses
---> 42 from .add_parent_mass import add_parent_mass
     43 from .add_precursor_mz import add_precursor_mz
     44 from .add_retention import add_retention_index, add_retention_time

File [~/code/new-metabolomics/.venv/lib/python3.9/site-packages/matchms/filtering/add_parent_mass.py:2](https://file+.vscode-resource.vscode-cdn.net/Users/shaurya/code/new-metabolomics/~/code/new-metabolomics/.venv/lib/python3.9/site-packages/matchms/filtering/add_parent_mass.py:2)
      1 import logging
----> 2 from matchms.filtering.filter_utils.derive_precursor_mz_and_parent_mass import \
      3     derive_parent_mass_from_precursor_mz
      4 from ..typing import SpectrumType
      5 from ..utils import get_first_common_element

ModuleNotFoundError: No module named 'matchms.filtering.filter_utils'
```

**Expected behavior**
for this to not happen

**Desktop (please complete the following information):**
 - OS: macOS 13.4.1 (22F82)
 - Version of matchms 0.21

**Comment by hechth** [comment]
Hi - we are aware of this problem and this should be solved in version 0.21.1

**Comment by hechth** [comment]
@chanana did this fix your issue? If so, this can be closed.

**Comment by chanana** [comment]
Yes! thank you! I have a new error instead. 

I again made a fresh environment via:

```shell
mkdir matchms-test
poetry init # set python 3.9 as default
poetry add matchms
```

```python
>>> from matchms import Spectrum

Configuration file exists at /Users/shaurya/Library/Preferences/pypoetry, reusing this directory.

Consider moving TOML configuration files to /Users/shaurya/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
Python 3.9.16 (main, Apr 24 2023, 11:18:10)
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from matchms import Spectrum
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shaurya/code/matchms-test/.venv/lib/python3.9/site-packages/matchms/__init__.py", line 8, in <module>
    from .Pipeline import Pipeline
  File "/Users/shaurya/code/matchms-test/.venv/lib/python3.9/site-packages/matchms/Pipeline.py", line 5, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
>>>
```

doing a `poetry add pyyaml` fixes it. Perhaps we could add `pyyaml` as a core dependency.
